/**
 * Batchwork – bulk user, group & alias operations for Google Workspace
 * Alias Manager: create, delete, export user aliases.
 */

/** 12. Create Aliases */
function createAliases(opts) {
  return processRows_({
    sheetName: '12. Create Aliases',
    interactive: isInteractive_(opts),
    required: ['User Email', 'Alias Email'],
    handler: function (row) {
      withRetry_(function () {
        return AdminDirectory.Users.Aliases.insert(
          { alias: String(row['Alias Email']) },
          String(row['User Email'])
        );
      });
      return 'Alias created';
    }
  });
}

/** 13. Delete User Aliases */
function deleteUserAliases(opts) {
  return processRows_({
    sheetName: '13. Delete User Aliases',
    interactive: isInteractive_(opts),
    required: ['User Email', 'Alias Email'],
    handler: function (row) {
      withRetry_(function () {
        return AdminDirectory.Users.Aliases.remove(String(row['User Email']), String(row['Alias Email']));
      });
      return 'Alias deleted';
    }
  });
}

/** 14. Export User Aliases */
function exportUserAliases(opts) {
  var sheetName = '14. Export User Aliases';
  var headers = ['User Email', 'Alias', 'Type'];
  var rows = [];
  setProgress_({ op: sheetName, phase: 'export', done: 0 });

  // Walk the whole directory. projection:'full' is required to get
  // nonEditableAliases — the default 'basic' projection omits them.
  var pageToken;
  do {
    var page = withRetry_(function () {
      return AdminDirectory.Users.list({
        customer: 'my_customer',
        maxResults: 500,
        orderBy: 'email',
        projection: 'full',
        pageToken: pageToken
      });
    });
    (page.users || []).forEach(function (u) {
      appendAliasRows_(rows, u.primaryEmail, u);
    });
    pageToken = page.nextPageToken;
    setProgress_({ op: sheetName, phase: 'export', done: rows.length });
  } while (pageToken);

  var count = writeExport_(sheetName, headers, rows, isInteractive_(opts));
  return { sheetName: sheetName, exported: count };
}

/**
 * Appends one row per alias for a user: manually added aliases plus the
 * non-editable ones generated by alias domains. Google's internal
 * *.test-google-a.com addresses are always excluded. Returns rows added.
 */
function appendAliasRows_(rows, userEmail, user) {
  var added = 0;
  (user.aliases || []).forEach(function (alias) {
    if (isTestDomainAlias_(alias)) return;
    rows.push([userEmail, alias, 'Editable']);
    added++;
  });
  (user.nonEditableAliases || []).forEach(function (alias) {
    if (isTestDomainAlias_(alias)) return;
    rows.push([userEmail, alias, 'Non-editable (domain alias)']);
    added++;
  });
  return added;
}

/** True for Google's internal test domain, e.g. user@acme.com.test-google-a.com. */
function isTestDomainAlias_(alias) {
  return /\.test-google-a\.com$/i.test(String(alias));
}
